- name: remove images
  command: bash -c 'if crictl inspecti "{{ registry }}/{{ repostory }}/{{ item }}-apparate" ;then crictl rmi "{{ registry }}/{{ repostory }}/{{ item }}-apparate" ; else exit 1;fi'
  with_items: "{{ case_images }}"
  changed_when:
  tags: ["clean"]
