apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: container
          image: fanjiankong-bj.tencentcloudcr.com/apparate/nginx:1.17.8
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 1
      terminationGracePeriodSeconds: 5
      nodeSelector:
        lab.kofj.net/docker: "true"
